sonar.projectKey=carecompanion-api
sonar.projectName=CareCompanion API
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true
